# Generated by Django 6.0.3 on 2026-03-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_tag_event_latitude_event_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The question to ask.', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('select', 'Dropdown Menu'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('choices', models.TextField(blank=True, help_text='For Dropdown: Enter options separated by commas.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
