# Generated by Django 6.0.2 on 2026-04-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the event page was viewed.'),
        ),
    ]
