# Generated by Django 6.0.3 on 2026-05-01 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Ideal ratio is 1.414 (A4 Landscape, e.g., 3508x2480px)', null=True, upload_to='cert_backgrounds/')),
                ('title', models.CharField(default='CERTIFICATE', max_length=100)),
                ('subtitle', models.CharField(default='Of Achievement', max_length=100)),
                ('primary_color', models.CharField(default='#1a2f4c', help_text='Hex color for main text and borders', max_length=20)),
                ('secondary_color', models.CharField(default='#d4af37', help_text='Hex color for subtitle', max_length=20)),
                ('text_color', models.CharField(default='#555555', help_text='Hex color for description text', max_length=20)),
                ('signature_title', models.CharField(default='Signature', max_length=50)),
                ('date_title', models.CharField(default='Date', max_length=50)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='events.event')),
            ],
        ),
    ]
