# Generated by Django 6.0.3 on 2026-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_certificatetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='date_title',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='signature_title',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='title',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='layout',
            field=models.JSONField(blank=True, default=dict, help_text='JSON mapping of elements (title, name, date, etc) to their x, y, font_size, and color.'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload your base certificate design (A4 Landscape, 3508x2480px)', null=True, upload_to='cert_backgrounds/'),
        ),
    ]
