# Generated by Django 6.0.2 on 2026-05-03 02:50

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_certificatetemplate_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload your base certificate design (A4 Landscape, 3508x2480px)', max_length=500, null=True, upload_to=events.models.get_cert_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text='Event banner image.', max_length=500, null=True, upload_to=events.models.get_banner_path),
        ),
    ]
