# Generated by Django 6.0.3 on 2026-03-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_business_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider_status',
            field=models.CharField(choices=[('none', 'Not Applied'), ('pending', 'Application Pending'), ('approved', 'Approved (Awaiting Payment)'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
