# Generated by Django 6.0.3 on 2026-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_commission_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offline_payment_requested',
            field=models.BooleanField(default=False),
        ),
    ]
