# Generated by Django 6.0.3 on 2026-03-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='provider_status',
            field=models.CharField(choices=[('none', 'Not Applied'), ('pending', 'Application Pending'), ('approved', 'Approved'), ('active', 'Active Organizer'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
