# Generated by Django 6.0.3 on 2026-03-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_provider_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Provider Application',
                'verbose_name_plural': 'Provider Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.userprofile',),
        ),
    ]
