# Generated by Django 6.0.3 on 2026-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registration_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('offline', 'Pay at Venue')], default='razorpay', max_length=20),
        ),
    ]
