# Generated by Django 6.0.3 on 2026-03-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_customfield'),
        ('registrations', '0004_registration_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='The answer provided by the attendee.')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='events.customfield')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Custom Field Value',
                'verbose_name_plural': 'Custom Field Values',
                'unique_together': {('registration', 'field')},
            },
        ),
    ]
