# Generated by Django 6.0.2 on 2026-05-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_customfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='qr_codes/'),
        ),
    ]
